# Generated by Django 5.0.4 on 2024-06-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя автора', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию автора', max_length=100, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL-адрес')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author_photos/', verbose_name='Фотография')),
                ('biography', models.TextField(blank=True, help_text='Краткая биография автора', verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=250, verbose_name='Название')),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN')),
                ('cover', models.ImageField(blank=True, upload_to='cover_images/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.PositiveIntegerField(verbose_name='Год издания')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Язык')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Издательство')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
