services:

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      volumes:
        - .:/usr/src/app/
      env_file:
        - ./.env.dev
      networks:
        - myshop_network
      restart: always

    postgres:
      image: postgres:latest
      ports:
        - "5432:5432"
      volumes:
        - ../myshop_data/pgdata/:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=myshop_db
        - POSTGRES_USER=myshop
        - POSTGRES_PASSWORD=1804036
      networks:
        - myshop_network
      restart: always

networks:
  myshop_network:
    driver: bridge
